import { Data } from "effect";

export const FACTORY_ERROR_CODES = [
  "admission_invariant_failed",
  "approval_requested",
  "assignment_failed",
  "assignment_id_invalid",
  "assignment_not_found",
  "child_startup_failed",
  "child_startup_timeout",
  "claim_unconfirmed",
  "claim_unknown",
  "cleanup_timeout",
  "clone_remote_mismatch",
  "codex_version_failed",
  "command_id_required",
  "config_arguments_invalid",
  "config_invalid",
  "config_read_failed",
  "fixture_arguments_invalid",
  "fixture_build_failed",
  "fixture_catalog_invalid",
  "fixture_production_forbidden",
  "git_command_failed",
  "git_command_invalid",
  "github_command_failed",
  "github_command_invalid",
  "github_discovery_failed",
  "github_response_invalid",
  "initialization_timeout",
  "integration_arguments_invalid",
  "integration_issue_create_failed",
  "integration_preflight_failed",
  "interrupt_timeout",
  "model_or_effort_unavailable",
  "model_rerouted",
  "model_schema_timeout",
  "model_unavailable",
  "non_loopback_bind_rejected",
  "observed_effort_mismatch",
  "observed_effort_missing",
  "observed_model_mismatch",
  "process_identity_changed",
  "provider_command_invalid",
  "provider_error_notification",
  "provider_exited",
  "provider_failed",
  "provider_protocol_error",
  "provider_rpc_error",
  "provider_schema_incompatible",
  "provider_stopped",
  "provider_timeout_invalid",
  "retention_config_invalid",
  "retained_record_invalid",
  "pull_request_unverified",
  "pull_request_verification_failed",
  "queue_page_invalid",
  "repository_invalid",
  "repository_not_configured",
  "issue_ineligible",
  "database_in_use",
  "database_reset_required",
  "dispatch_paused",
  "codex_disabled",
  "schema_generation_failed",
  "service_start_failed",
  "service_shutdown",
  "starting_commit_invalid",
  "state_store_failed",
  "page_invalid",
  "page_watermark_invalid",
  "thread_id_missing",
  "token_usage_missing",
  "turn_completion_timeout",
  "turn_id_missing",
  "turn_not_completed",
  "unexpected_error",
  "workflow_invalid",
  "workspace_create_failed",
  "workspace_path_escape",
  "worktree_exists",
] as const;
export type FactoryErrorCode = (typeof FACTORY_ERROR_CODES)[number];

export class FactoryError extends Data.TaggedError("FactoryError")<{
  readonly code: FactoryErrorCode;
  readonly message: string;
  readonly detail?: string;
}> {}

export function asFactoryError(
  error: unknown,
  code: FactoryErrorCode = "unexpected_error",
): FactoryError {
  if (error instanceof FactoryError) return error;
  return new FactoryError({ code, message: String(error) });
}
